---
- name: Upgrade OS
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: "{{ upgrade_cache_valid_time }}"

- name: Install dependencies
  apt:
    name: 
      - curl
      - net-tools
      - bluez
    state: present

- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true

- name: Install python3-kubernetes
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present
  become: true

# Necessary for cloudflare operator
# https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
- name: Set net.core.rmem_max to 7500000
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: '7500000'
    sysctl_set: yes
    state: present
    reload: yes
  become: true

# Necessary for cloudflare operator
# https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
- name: Set net.core.wmem_max to 7500000
  ansible.posix.sysctl:
    name: net.core.wmem_max
    value: '7500000'
    sysctl_set: yes
    state: present
    reload: yes
  become: true

- name: Create symlink for k3s kubeconfig
  ansible.builtin.file:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    state: link

- name: Install k9s via official Debian package
  ansible.builtin.shell: |
    wget https://github.com/derailed/k9s/releases/download/v0.50.6/k9s_linux_arm64.deb -O /tmp/k9s_linux_arm64.deb
    apt install -y /tmp/k9s_linux_arm64.deb
    rm /tmp/k9s_linux_arm64.deb
  args:
    executable: /bin/bash
  become: true

- name: Install kubectx
  ansible.builtin.package:
    name: kubectx
    state: present
