---
- name: Copy Home Assistant manifest from template
  ansible.builtin.template:
    src: home-assistant.yaml.j2
    dest: /tmp/home-assistant.yaml

- name: Apply Home Assistant manifests
  kubernetes.core.k8s:
    state: present
    src: /tmp/home-assistant.yaml
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Wait for Home Assistant StatefulSet to be ready
  become: false
  shell: |
    kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml rollout status statefulset/home-assistant -n home-assistant
  register: home_assistant_rollout
  retries: 10
  delay: 15
  until: home_assistant_rollout.rc == 0

- name: Copy secrets file
  ansible.builtin.template:
    src: secrets.yaml.j2
    dest: /tmp/secrets.yaml

- name: Copy Home Assistant configuration block to Raspberry Pi
  become: false
  copy:
    src: "{{ role_path }}/files/configuration.yaml"
    dest: /tmp/configuration.yaml
    mode: '0644'

- name: Add configurations inside Home Assistant pod
  become: false
  shell: |
    sleep 20
    cat /tmp/configuration.yaml | kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml exec -i -n home-assistant statefulset/home-assistant -- \
    sh -c 'cat > /config/configuration.yaml'
    cat /tmp/secrets.yaml | kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml exec -i -n home-assistant statefulset/home-assistant -- \
    sh -c 'cat > /config/secrets.yaml'
  register: add_configuration

- name: Install HACS
  become: false
  shell: |
    kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml exec -it home-assistant-0 \
      -n home-assistant -- sh -c "wget -qO - https://get.hacs.xyz | bash -"

- name: Install Cloudflare Operator
  become: false
  shell: |
    kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml apply -k  https://github.com/adyanth/cloudflare-operator/config/default\?ref\=v0.12.0

- name: Render Cloudflare Tunnel manifest
  ansible.builtin.template:
    src: cloudflare_tunnel.yaml.j2
    dest: /tmp/cloudflare_tunnel.yaml

- name: Apply Cloudflare Tunnel manifest
  kubernetes.core.k8s:
    state: present
    src: /tmp/cloudflare_tunnel.yaml
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Restart Home Assistant pod to reload configuration
  become: false
  shell: |
    kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml rollout restart statefulset/home-assistant -n home-assistant
  register: restart_home_assistant

- name: Copy vscode manifest from template
  ansible.builtin.template:
    src: vscode.yaml.j2
    dest: /tmp/vscode.yaml

- name: Apply vscode manifests
  kubernetes.core.k8s:
    state: present
    src: /tmp/vscode.yaml
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Wait for vscode StatefulSet to be ready
  become: false
  shell: |
    kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml rollout status statefulset/code-server -n home-assistant
  register: code_server_rollout
  retries: 10
  delay: 15
  until: code_server_rollout.rc == 0

